### ISSUE TITLE
팀 이름과 프로젝트 이름 정하기

### ISSUE THREAD

**Issue by wynter122** [wynter122/Capstone-Project-2023-1#1]
현재 팀 명은 정해지지 않았고, 프로젝트명은 제가 임시로 KMU-Recycle 로 부르고 있습니다.
프로젝트명은 레포지토리 이름을 정해야 하기 때문에 빨리 정하는게 좋을 것 같습니다. 

키워드는 Recycle, 쓰레기, 이미지, 재활용, 분리수거 등이 있는 것 같은데, 굳이 이 키워드를 쓰지 않아도 프로젝트 방향성을 나타낼 수 있는 이름이면 좋을 것 같습니다.
좋은 아이디어 있으면 자유롭게 말씀해주세요.

**Comment by lucyya99** [comment]
저희가 낸 아이디어가 사회적인 측면에서 도움이 될 만한 것들이라서 팀명을 '이로운'이나 연결한다는 의미에서 '브릿지' 생각해봤습니다. 그리고 '네모칸의한줄'은 조금 추상적이긴한데, 누군가가 그어둔 경계선을 네모칸 위에서 바라본다는 의미에서 생각해봤습니다. 네모칸 위에서보면 칸으로 나눠진 양쪽 입장이 다 보이기 때문에 우리가 양쪽 입장을 고려한 세상을 보겠다는 의미입니다. 또 의견 생기면 내볼게요!

**Comment by lucyya99** [comment]
> 저희가 낸 아이디어가 사회적인 측면에서 도움이 될 만한 것들이라서 팀명을 '이로운'이나 세상을 연결한다는 의미에서 '브릿지' 생각해봤습니다. 그리고 '네모칸의한줄'은 조금 추상적이긴한데, 누군가가 그어둔 경계선을 네모칸 위에서 바라본다는 의미에서 생각해봤습니다. 네모칸 위에서보면 칸으로 나눠진 양쪽 입장이 다 보이기 때문에 우리가 양쪽 입장을 고려한 세상을 보겠다는 의미입니다. 또 의견 생기면 내볼게요!

**Comment by wynter122** [comment]
- Shoot the Trash
버릴 쓰레기 사진을 찍는 어플이기 때문에 Shoot (사진찍다) + Trash (쓰레기) 를 생각해봤습니다.

@lucyya99 가 생각하신 팀명 '이로운' 괜찮은 것 같아요

**Comment by wynter122** [comment]
주제 변경으로 Close
