### ISSUE TITLE
기초 학습 데이터 선별

### ISSUE THREAD

**Issue by dh5473** [wynter122/Capstone-Project-2023-1#2]
https://www.aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=realm&dataSetSn=140

위 링크에 올라와있는 생활 폐기물 이미지 데이터는 크게 15종류로 이루어져 있습니다.
그 안에서 또 세부 종류가 있고, 총 이미지는 75만장으로 각 class에 따라 균등하게 배분되어 있습니다.

코랩 상에서 학습을 진행하면 (이미지 크기에 따라 다르지만) 만 장만 되어도 RAM이 터지는 경우가 많아 어느 정도 선별해서 학습시켜야 할 것 같습니다.

https://donhdonot.notion.site/Detection-66f3e27c412e4864a3f34876cf167c17

크게 15가지 class 중 10가지를 사용하려하는데, 제외할 종류를 위 노션 페이지에 표시해두었습니다.
이견 혹은 궁금한 점 있으시면 comment 남겨주세요.

**Comment by wynter122** [comment]
선별 과정에서 제외 이유가 특별하게 있을까요?

어플리케이션 목적이 "헷갈리는 폐기물의 처리 방법을 제시한다" 인 만큼 평소에 잘 버리지 않는 폐기물들 위주의 데이터가 많이 들어가야할 것 같은데, 선별된 데이터셋에서는 평소에 자주 버리는 폐기물 위주로 선별 된 느낌이 다소 드는 것 같습니다.

**Comment by dh5473** [comment]
말씀하신대로 헷갈리는 폐기물은 페트병, 플라스틱, 스티로폼 등 외관상 비슷해보이는 유형이라고 생각했습니다. 반면에 가구류, 자전거, 형광등 같은 폐기물들은 누가봐도 알 수 있다고 생각해서요. 다만 버리는 방법이 헷갈리는 경우에는 비주류 폐기물도 넣어야겠네요.

이게 전자제품 같은 경우 세부분류가 너무 많아서.. 세부 클래스까지 분류하기에는 어려움이 있을 거 같아 제외하기는 했습니다. 회의 때 이야기해봐요!

**Comment by wynter122** [comment]
네 좋아요. 
구글폼으로 설문지를 만들어서 그 결과를 토대로 데이터를 선별해도 좋을 것 같아요.
물론 이 방법은 설문 결과를 많이 얻어내야 의미가 있겠지만, 시도해보는것도 좋을 듯 합니다.

**Comment by wynter122** [comment]
주제변경으로 close
