### ISSUE TITLE
분리배출 표시 마크를 데이터셋에 포함할 수 있는지

### ISSUE THREAD

**Issue by wynter122** [wynter122/Capstone-Project-2023-1#3]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/72314987/210305021-369c2eb5-1789-4c7b-8b3e-a65ff67f5f3b.png">

위 사진과 같이 분리배출 표시 마크도 데이터셋에 포함하면 어떨지 궁금합니다.
데이터셋을 조사해보았는데, ai hub에는 없는 것 같고,  https://www.keco.or.kr/kr/business/resource/contentsid/1564/index.do 에서 다운받을 수 있습니다. 
저 데이터만으로 훈련이 가능할지, 만약 데이터가 부족하다면 수작업으로 가능한 작업이 될까요?

+ ai hub 외에 다른 데이터셋이 있는지는 아직 파악되지 않았습니다.

**Comment by dh5473** [comment]
페이지 들어가서 확인해봤는데 이미지가 딱 한 장씩 있더라고요. 학습시키려면 각 종류별로 최소로 잡아도 100장..? 은 필요할 거 같아요. 그리고 디텍션 모델은 각 이미지 데이터에 해당하는 바운딩 박스와 클래스 분류 정보가 필요해서 해당 자료로는 힘들 것 같네요.

모델 만들게 되면 분리배출 표시 없이도 어떤 재활용 분류를 해야하는지 알 수 있을텐데, 분리배출 표시를 포함하고 싶은 이유가 있으신가요? 특별한 이유 있으시면 저도 찾아볼게요!

**Comment by wynter122** [comment]
배출 표시 마크중에서 플라스틱과 비닐류의 경우 아래에 쓰여진 글자에 따라 배출 방식이 약간식 달라진다고 알고 있습니다.
<img width="726" alt="image" src="https://user-images.githubusercontent.com/72314987/210705570-16fc0e3a-f7c8-4fc3-9b6d-17860cd1ed5c.png">

이런 부분도 배출 방식을 구별해서 제공하면 좋을 것 같다고 생각했어요. 
데이터셋 확보가 가능하다면, 사물인식과 라벨인식 두가지로 기능을 나눌수 있지 않을까? 라는 생각을 했습니다.

**Comment by dh5473** [comment]
보내주신 이미지에는 글씨가 매우 선명하게 되어 있지만, 실제로는 정확히 규격화된 이미지를 얻기가 힘듭니다. 글씨가 매우 작거나, 형식이 조금씩 다르거나요. 해봐야 알겠지만 Detection으로 안된다면, OCR을 활용해보는 것도 좋겠어요.

**Comment by wynter122** [comment]
네 그러면 OCR이 가능하다면 확인해보고 추가기능으로 개발해도 될 것 같네요
확인 감사합니다1

**Comment by wynter122** [comment]
주제 변경으로 close
